### ISSUE TITLE
swipe  animation card code is not working 

### ISSUE THREAD

**Issue by vubon** [GeekyAnts/flutter-docs-code-samples#3]
"A function type String  container can't be assigned to a location of type dynamic container"

**Comment by vubon** [comment]
Sorry problem fixed 

need to here modify : 

 children: cards.map((String card) to  children: cards.map((dynamic card)

**Comment by Samaritan1011001** [comment]
Thanks for pointing it out @vubon. I have updated the code.

**Comment by vubon** [comment]
welcome :) thanks too ..

**Comment by AshokVonteddu** [comment]
Error: Method not found: 'createHttpClient'.
 final httpClient = createHttpClient();
